name: Deploy to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 using CodeDeploy
      uses: aws-actions/aws-codedeploy-github-actions@v1
      with:
        application-name: mockingbird
        deployment-group-name: EC2-Front
        deployment-config-name: CodeDeployDefault.AllAtOnce
        github-token: ${{ secrets.GITHUB_TOKEN }}
        region: eu-west-3
